### ISSUE TITLE
关于最后fc层

### ISSUE THREAD

**Issue by talentCODE** [sud0301/essentials_for_CIL#1]
你好，请问你尝试使用常规fc层做实验而非cosinelinear吗？如果尝试过，在论文算法下，两种分类器对比怎么样？  

还有在使用cosinelinear分类器，我训练自己数据集，发现sigma固定增加，模型很快（10个epoch样子）就达到最佳，继续性能就会降得很快，你在训练中是否有该现象。

**Comment by sud0301** [comment]
Yes, I tried with fc layer as well. Cosinelinear layer shows an improvement of approximately 1-1.5% on average incremental accuracy for CIFAR-100 dataset. 

I did not notice such a phenomema, I would recommend changing the <w-kd> hyperparameter to find the right balance between CE and KD loss.

**Comment by talentCODE** [comment]
thanks for your reply!
